
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVAILABLE AVAILABLE_C AVAILABLE_O BRAND_C BRAND_O CARS_C CARS_O CAR_C CAR_O DATE DATE_C DATE_O DESCRIPTION_C DESCRIPTION_O ID ID_C ID_O LICENSE_PLATE LICENSE_PLATE_C LICENSE_PLATE_O MODEL_C MODEL_O RENTAL_PRICE RENTAL_PRICE_C RENTAL_PRICE_O SERVICES_C SERVICES_O SERVICE_C SERVICE_O TEXT TRANSMISSION TRANSMISSION_C TRANSMISSION_O YEAR YEAR_C YEAR_Ocars : CARS_O car_list CARS_Ccar_list : car car_listcar_list : car : CAR_O id brand model year license_plate available rental_price transmission services CAR_Cid : ID_O ID ID_Cbrand : BRAND_O TEXT BRAND_Cmodel : MODEL_O TEXT MODEL_Cyear : YEAR_O YEAR YEAR_Clicense_plate : LICENSE_PLATE_O LICENSE_PLATE LICENSE_PLATE_Cavailable : AVAILABLE_O AVAILABLE AVAILABLE_Crental_price : RENTAL_PRICE_O RENTAL_PRICE RENTAL_PRICE_Ctransmission : TRANSMISSION_O TRANSMISSION TRANSMISSION_Cservices : SERVICES_O service_list SERVICES_Cservice_list : service service_listservice_list : service : SERVICE_O date description SERVICE_Cdate : DATE_O DATE DATE_Cdescription : DESCRIPTION_O TEXT DESCRIPTION_C'
    
_lr_action_items = {'CARS_O':([0,],[2,]),'$end':([1,6,],[0,-1,]),'CARS_C':([2,3,4,7,41,],[-3,6,-3,-2,-4,]),'CAR_O':([2,4,41,],[5,5,-4,]),'ID_O':([5,],[9,]),'BRAND_O':([8,16,],[11,-5,]),'ID':([9,],[12,]),'MODEL_O':([10,20,],[14,-6,]),'TEXT':([11,14,51,],[15,19,54,]),'ID_C':([12,],[16,]),'YEAR_O':([13,24,],[18,-7,]),'BRAND_C':([15,],[20,]),'LICENSE_PLATE_O':([17,28,],[22,-8,]),'YEAR':([18,],[23,]),'MODEL_C':([19,],[24,]),'AVAILABLE_O':([21,32,],[26,-9,]),'LICENSE_PLATE':([22,],[27,]),'YEAR_C':([23,],[28,]),'RENTAL_PRICE_O':([25,36,],[30,-10,]),'AVAILABLE':([26,],[31,]),'LICENSE_PLATE_C':([27,],[32,]),'TRANSMISSION_O':([29,40,],[34,-11,]),'RENTAL_PRICE':([30,],[35,]),'AVAILABLE_C':([31,],[36,]),'SERVICES_O':([33,45,],[38,-12,]),'TRANSMISSION':([34,],[39,]),'RENTAL_PRICE_C':([35,],[40,]),'CAR_C':([37,46,],[41,-13,]),'SERVICES_C':([38,42,43,47,53,],[-15,46,-15,-14,-16,]),'SERVICE_O':([38,43,53,],[44,44,-16,]),'TRANSMISSION_C':([39,],[45,]),'DATE_O':([44,],[49,]),'DESCRIPTION_O':([48,55,],[51,-17,]),'DATE':([49,],[52,]),'SERVICE_C':([50,56,],[53,-18,]),'DATE_C':([52,],[55,]),'DESCRIPTION_C':([54,],[56,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cars':([0,],[1,]),'car_list':([2,4,],[3,7,]),'car':([2,4,],[4,4,]),'id':([5,],[8,]),'brand':([8,],[10,]),'model':([10,],[13,]),'year':([13,],[17,]),'license_plate':([17,],[21,]),'available':([21,],[25,]),'rental_price':([25,],[29,]),'transmission':([29,],[33,]),'services':([33,],[37,]),'service_list':([38,43,],[42,47,]),'service':([38,43,],[43,43,]),'date':([44,],[48,]),'description':([48,],[50,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cars","S'",1,None,None,None),
  ('cars -> CARS_O car_list CARS_C','cars',3,'p_cars','yacc.py',10),
  ('car_list -> car car_list','car_list',2,'p_car_list','yacc.py',16),
  ('car_list -> <empty>','car_list',0,'p_car_list_empty','yacc.py',23),
  ('car -> CAR_O id brand model year license_plate available rental_price transmission services CAR_C','car',11,'p_car','yacc.py',29),
  ('id -> ID_O ID ID_C','id',3,'p_id','yacc.py',36),
  ('brand -> BRAND_O TEXT BRAND_C','brand',3,'p_brand','yacc.py',42),
  ('model -> MODEL_O TEXT MODEL_C','model',3,'p_model','yacc.py',48),
  ('year -> YEAR_O YEAR YEAR_C','year',3,'p_year','yacc.py',54),
  ('license_plate -> LICENSE_PLATE_O LICENSE_PLATE LICENSE_PLATE_C','license_plate',3,'p_license_plate','yacc.py',60),
  ('available -> AVAILABLE_O AVAILABLE AVAILABLE_C','available',3,'p_available','yacc.py',66),
  ('rental_price -> RENTAL_PRICE_O RENTAL_PRICE RENTAL_PRICE_C','rental_price',3,'p_rental_price','yacc.py',72),
  ('transmission -> TRANSMISSION_O TRANSMISSION TRANSMISSION_C','transmission',3,'p_transmission','yacc.py',78),
  ('services -> SERVICES_O service_list SERVICES_C','services',3,'p_services','yacc.py',84),
  ('service_list -> service service_list','service_list',2,'p_service_list','yacc.py',90),
  ('service_list -> <empty>','service_list',0,'p_service_list_empty','yacc.py',99),
  ('service -> SERVICE_O date description SERVICE_C','service',4,'p_service','yacc.py',105),
  ('date -> DATE_O DATE DATE_C','date',3,'p_date','yacc.py',111),
  ('description -> DESCRIPTION_O TEXT DESCRIPTION_C','description',3,'p_description','yacc.py',117),
]
